name: Update README cards

on:
  schedule:
    - cron: "45 1 * * *"
  workflow_dispatch:
    inputs:
      message:
        description: "Commit Message"
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate dark mode stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&count_private=true&theme=highcontrast&bg_color=60,353535,111111&title_color=eee&text_color=eee&line_height=20&custom_title=GitHub%20Stats&hide_border=true&border_radius=5&include_all_commits=true&hide_title=true&rank_icon=github&text_bold=false&icon_color=00897b&show=discussions_started&ring_color=545454
          path: profile/stats-dark.svg
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Generate light mode stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&count_private=true&theme=highcontrast&bg_color=60,ffffff,dcdcdc&title_color=eee&text_color=323232&line_height=20&custom_title=GitHub%20Stats&hide_border=true&border_radius=5&include_all_commits=true&hide_title=true&rank_icon=github&text_bold=true&icon_color=00897b&show=discussions_started&ring_color=ababab
          path: profile/stats-light.svg
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Commit cards
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

          git add profile/*.svg

          COMMIT_MESSAGE="${{ github.event.inputs.message }}"
          COMMIT_MESSAGE="${COMMIT_MESSAGE:-Update README cards}"

          git commit -m "$COMMIT_MESSAGE" || exit 0
          git push
